const PLAYER_TEAM_MAP = {
  KAWA: "Pilgrims",
  JR: "Reindeer",
  DETHORNE: "Team Santa",
  ELFFAW: "Turkeys",
  "ANDY MAC": "Reindeer",
  TWERP: "Pumpkins",
  MATTAUX: "Pumpkins",
  KAWA2796: "Pilgrims",
  PNKROCKJOCK26: "Pumpkins",
  HOOTENANNIES: "Pilgrims",
  OFTHEMOON16: "Death",
  "GNOMIE, DONT YA KNOW ME?": "Death",
  GOLFJBC89: "Turkeys",
  JMYRV: "Turkeys",
  MADSCOUTFAN: "Death",
  MADSCOUT: "Death",
  KURTZYP00: "Team Santa",
  "KURTZY P00": "Team Santa",
  "SNAKES ON A MICROPLANE": "Reindeer",
  EVERGREEN6258: "Team Santa",
  "CREAM DADDY9057": "Team Santa",

  /*
   "KAWA": "india",
   "DETHORNE": "venezuela",
   "ELFFAW": "switzerland",
   "ANDY MAC": "switzerland",
   "TWERP": "somalia",
   "MATTAUX": "venezuela",
   "PNKROCKJOCK26": "thailand",
   "OFTHEMOON16": "australia",
   "GOLFJBC89": "australia",
   "MADSCOUTFAN": "somalia",
   "MADSCOUT": "somalia",
   "KURTZYP00": "thailand",
   "KURTZY P00": "thailand",
   "EVERGREEN6258": "panama",
   */

  DUDE: "Death",
  BUZZ: "Turkeys",
  FURY: "Turkeys",
  BANDIT: "Turkeys",
  WOLFMAN: "Death",
  HOUND: "Turkeys",
  CENTICE: "Death",
  MOUNTAIN: "Death",
  SALTIE: "Turkeys",
  PONCHO: "Death",
  SUNDOWN: "Death",
  ARMSTRONG: "Turkeys",
  FOAMER: "Death",
  CHIPPER: "Turkeys",
  TUSK: "Turkeys",
  STORM: "Turkeys",
  VIPER: "Tukerys",
  OUTLAW: "Death",
  CASPER: "Death",
  MIDDY: "Death",
  JUNKER: "Turkeys",
  TEX: "Turkeys",
  SCOUT: "Death",
  MARLEY: "Turkeys",
  REX: "Turkeys",
  YURI: "Death",
  COUGAR: "Death",
  SHEPARD: "Pumpkins",
  HOLLYWOOD: "Pumpkins",
};

const TEAM_LOGO_MAP = {
  RLL: "assets/RLL_logo.png",
  Pilgrims: "assets/LOGO_PILGRIMS.png",
  "Team Santa": "assets/LOGO_SANTA.png",
  Reindeer: "assets/LOGO_REINDEER.png",
  Turkeys: "assets/LOGO_TURKEYS.png",
  Pumpkins: "assets/LOGO_PUMPKINS.png",
  Death: "assets/LOGO_DEATH.png",

  australia: "assets/FLAG_AUSTRALIA.png",
  india: "assets/FLAG_INDIA.png",
  panama: "assets/FLAG_PANAMA.png",
  switzerland: "assets/FLAG_SWISS.png",
  thailand: "assets/FLAG_THAILAND.png",
  venezuela: "assets/FLAG_VENEZUELA.png",
  somalia: "assets/FLAG_SOMALIA.png",
};

const TEAM_COLOR_MAP = {
  RLL: {
    primary: "crimson",
    secondary: "white",
    shadow: "white",
    tertiary: "black",
  },
  Pilgrims: {
    primary: "#faebd7",
    secondary: "#800000",
    shadow: "black",
    tertiary: "black",
  },
  "Team Santa": {
    primary: "#b70407",
    secondary: "#eaeaea",
    shadow: "black",
    tertiary: "black",
  },
  Reindeer: {
    primary: "#0d340a",
    secondary: "#f0eeef",
    shadow: "black",
    tertiary: "black",
  },
  Turkeys: {
    primary: "#7c471b",
    secondary: "#ffcc33",
    shadow: "#4d2c10",
    tertiary: "black",
  },
  Pumpkins: {
    primary: "#ff8800",
    secondary: "black",
    shadow: "#ffbf00",
    tertiary: "black",
  },
  Death: {
    primary: "#182024",
    secondary: "#6b99ae",
    shadow: "black",
    tertiary: "black",
  },

  australia: {
    primary: "#101f4f",
    secondary: "white",
    shadow: "black",
    tertiary: "black",
  },
  india: {
    primary: "#e27423",
    secondary: "white",
    shadow: "#d86619",
    tertiary: "black",
  },
  panama: {
    primary: "#e9f3f4",
    secondary: "#d21034",
    shadow: "black",
    tertiary: "black",
  },
  switzerland: {
    primary: "#c41616",
    secondary: "white",
    shadow: "black",
    tertiary: "black",
  },
  thailand: {
    primary: "#07304f",
    secondary: "white",
    shadow: "black",
    tertiary: "black",
  },
  venezuela: {
    primary: "#ffbc00",
    secondary: "#cf142b",
    shadow: "black",
    tertiary: "black",
  },
  somalia: {
    primary: "##1980bf",
    secondary: "white",
    shadow: "black",
    tertiary: "black",
  },
};
