/*
const PLAYER_TEAM_MAP = {
  AWESOMEX: "BRAN",
  KAWA: "TOAST",
  JR: "SMACKS",
  DETHORNE: "CRUNCH",
  ELFFAW: "SMACKS",
  "ANDY MAC": "TRIX",
  TWERP: "FROOTS",
  MATTAUX: "CHARMS",
  KAWA2796: "BRAN",
  PNKROCKJOCK26: "KRISPIES",
  HOOTENANNIES: "KRISPIES",
  OFTHEMOON16: "CHEERIOS",
  GOLFJBC89: "FROOTS",
  JMYRV: "CHEERIOS",
  MADSCOUTFAN: "CHARMS",
  MADSCOUT: "CHARMS",
  KURTZYP00: "TOAST",
  "KURTZY P00": "TOAST",
  "SNAKES ON A MICROPLANE": "FLAKES",
  EVERGREEN6258: "TRIX",
  "CREAM DADDY9057": "TOAST",
  FATKIDDESTROYERS: "FLAKES",
  NKSSOCCER15: "CRUNCH",

  ARMSTRONG: "FRANCE",
  STORM: "FRANCE",
  CHIPPER: "CHINA",
  COUGAR: "MEXICO",
  FURY: "EGYPT",
  CAVEMAN: "MEXICO",
  PONCHO: "MEXICO",
  SHEPARD: "MEXICO",
  CENTICE: "FRANCE",
  MIDDY: "FRANCE",
  OUTLAW: "UKRAINE",
  ROUNDHOUSE: "UKRAINE",
  SUNDOWN: "CHINA",
  "C-BLOCK": "ICELAND",
  SULTAN: "EGYPT",
  CASPER: "RWANDA",
  ICEMAN: "UKRAINE",
  SQUALL: "EGYPT",
  BOOMER: "ICELAND",
  JUNKER: "RWANDA",
  SWABBIE: "ICELAND",
  JESTER: "GUATEMALA",
  HOLLYWOOD: "FRANCE",
  ARMSTRONG: "FRANCE",
  TUSK: "RWANDA",
  FOAMER: "CHINA",
  MYRTLE: "UKRAINE",
  MARLEY: "GUATEMALA",
  RAINMAKER: "GUATEMALA",
  SCOUT: "MEXICO",
  BANDIT: "GUATEMALA",
  GERWIN: "FRANCE",
  TEX: "FRANCE",
  YURI: "UKRAINE",
  MIDDY: "FRANCE",
  WOLFMAN: "CHINA",
  MOUNTAIN: "CHINA",
  SAMARA: "ICELAND",
  STICKS: "CHINA",
  KHAN: "ICELAND",
  SALTIE: "MEXICO",
  SABERTOOTH: "CHINA",
  STINGER: "CHINA",
  OUTLAW: "GUATEMALA",
};
*/
const PLAYER_TEAM_MAP = {
  AWESOMEX: "FRANCE",
  KAWA: "CHINA",
  JR: "SMACKS",
  DETHORNE: "EGYPT",
  ELFFAW: "ICELAND",
  "ANDY MAC": "GUATEMALA",
  TWERP: "FROOTS",
  MATTAUX: "ICELAND",
  KAWA2796: "RWANDA",
  PNKROCKJOCK26: "EGYPT",
  HOOTENANNIES: "UKRAINE",
  OFTHEMOON16: "CHEERIOS",
  GOLFJBC89: "MEXICO",
  JMYRV: "UKRAINE",
  MADSCOUTFAN: "GUATEMALA",
  MADSCOUT: "GUATEMALA",
  KURTZYP00: "MEXICO",
  "KURTZY P00": "MEXICO",
  "SNAKES ON A MICROPLANE": "FLAKES",
  EVERGREEN6258: "RWANDA",
  "CREAM DADDY9057": "MEXICO",
  FATKIDDESTROYERS: "FRANCE",
  NKSSOCCER15: "CHINA",

  ARMSTRONG: "FRANCE",
  STORM: "FRANCE",
  CHIPPER: "CHINA",
  COUGAR: "MEXICO",
  FURY: "EGYPT",
  CAVEMAN: "MEXICO",
  PONCHO: "MEXICO",
  SHEPARD: "MEXICO",
  CENTICE: "FRANCE",
  MIDDY: "FRANCE",
  OUTLAW: "UKRAINE",
  ROUNDHOUSE: "UKRAINE",
  SUNDOWN: "CHINA",
  "C-BLOCK": "ICELAND",
  SULTAN: "EGYPT",
  CASPER: "RWANDA",
  ICEMAN: "UKRAINE",
  SQUALL: "EGYPT",
  BOOMER: "ICELAND",
  JUNKER: "RWANDA",
  SWABBIE: "ICELAND",
  JESTER: "GUATEMALA",
  HOLLYWOOD: "FRANCE",
  ARMSTRONG: "FRANCE",
  TUSK: "RWANDA",
  FOAMER: "CHINA",
  MYRTLE: "UKRAINE",
  MARLEY: "GUATEMALA",
  RAINMAKER: "GUATEMALA",
  SCOUT: "MEXICO",
  BANDIT: "GUATEMALA",
  GERWIN: "FRANCE",
  TEX: "FRANCE",
  YURI: "UKRAINE",
  MIDDY: "FRANCE",
  WOLFMAN: "CHINA",
  MOUNTAIN: "CHINA",
  SAMARA: "ICELAND",
  STICKS: "CHINA",
  KHAN: "ICELAND",
  SALTIE: "MEXICO",
  SABERTOOTH: "CHINA",
  STINGER: "CHINA",
  OUTLAW: "GUATEMALA",
};

/*
const TEAM_LOGO_MAP = {
  RLL: "assets/RLL_logo.png",
  KRLL: "assets/RLL_LOWER_LOGO.png",
  TOAST: "assets/LOGO_CRM_DAD.png",
  BRAN: "assets/LOGO_RAISIN.png",
  CRUNCH: "assets/LOGO_CRUNCH.png",
  SMACKS: "assets/LOGO_SMACKS.png",
  TRIX: "assets/LOGO_TRIX.png",
  FROOTS: "assets/LOGO_LOOPS.png",
  KRISPIES: "assets/LOGO_KRISPIES.png",
  FLAKES: "assets/LOGO_FLAKES.png",
  CHEERIOS: "assets/LOGO_CHERRIOS.png",
  CHARMS: "assets/LOGO_LUCKY.png",
};
*/

const TEAM_LOGO_MAP = {
  RLL: "assets/RLL_Logo_INTL.png",
  UKRAINE: "assets/FLAG_UKRAINE.png",
  CHINA: "assets/FLAG_CHINA.png",
  FRANCE: "assets/FLAG_FRANCE.png",
  GUATEMALA: "assets/FLAG_GUATEMALA.png",
  ICELAND: "assets/FLAG_ICELAND.png",
  MEXICO: "assets/FLAG_MEXICO.png",
  RWANDA: "assets/FLAG_RWANDA.png",
  EGYPT: "assets/FLAG_EGYPT.png",
};

const TEAM_LEAGUE_MAP = {
  RLL: 1,
  TOAST: 1,
  BRAN: 1,
  CRUNCH: 2,
  SMACKS: 2,
  TRIX: 1,
  FROOTS: 2,
  KRISPIES: 2,
  FLAKES: 2,
  CHEERIOS: 1,
  CHARMS: 1,
};

const AVG_SCORE_MAP = {
  KAWA: 578,
  JR: 245,
  DETHORNE: 357,
  ELFFAW: 541,
  "ANDY MAC": 309,
  TWERP: 431,
  MATTAUX: 277,
  KAWA2796: 181,
  PNKROCKJOCK26: 349,
  HOOTENANNIES: 280,
  OFTHEMOON16: 433,
  "GNOMIE, DONT YA KNOW ME?": 441,
  GOLFJBC89: 392,
  JMYRV: 354,
  MADSCOUTFAN: 394,
  MADSCOUT: 394,
  KURTZYP00: 328,
  "KURTZY P00": 328,
  "CREAM DADDY9057": 328,
  "SNAKES ON A MICROPLANE": 481,
  EVERGREEN6258: 599,
  AWESOMEX: 761,
  FATKIDDESTROYERS: 207,
  NKSSOCCER15: 181,

  WOLFMAN: 521,
  SALTIE: 154,
};

/*
const TEAM_TRANSITION_MAP = {
  RLL: "assets/RLL_Logo_LARGE.png",
  TOAST: "assets/svg/LOGO_TOAST.svg",
  BRAN: "assets/svg/LOGO_RAISIN_BRAN.svg",
  CRUNCH: "assets/svg/LOGO_CRUNCH.svg",
  SMACKS: "assets/svg/LOGO_SMACKS.svg",
  TRIX: "assets/svg/LOGO_TRIX.svg",
  FROOTS: "assets/svg/LOGO_FRUIT_LOOPS.svg",
  KRISPIES: "assets/svg/LOGO_KRISPIES.svg",
  FLAKES: "assets/svg/LOGO_FROSTED_FLAKES.svg",
  CHEERIOS: "assets/svg/LOGO_CHEERIOS.svg",
  CHARMS: "assets/svg/LOGO_LUCKY_CHARMS.svg",
};
*/

const TEAM_TRANSITION_MAP = {
  RLL: "assets/RLL_Logo_LARGE.png",
  UKRAINE: "assets/svg/FLAG_UKRAINE.svg",
  CHINA: "assets/svg/FLAG_CHINA.svg",
  FRANCE: "assets/svg/FLAG_FRANCE.svg",
  GUATEMALA: "assets/svg/FLAG_GUATEMALA.svg",
  ICELAND: "assets/svg/FLAG_ICELAND.svg",
  MEXICO: "assets/svg/FLAG_MEXICO.svg",
  RWANDA: "assets/svg/FLAG_RWANDA.svg",
  EGYPT: "assets/svg/FLAG_EGYPT.svg",
};

const TEAM_COLOR_MAP = {
  RLL: {
    primary: "crimson",
    secondary: "white",
    shadow: "white",
    tertiary: "black",
  },
  CHARMS: {
    primary: "#499f5a",
    secondary: "white",
    shadow: "fc5e00",
    tertiary: "black",
  },
  FLAKES: {
    primary: "#ff6534",
    secondary: "#3651a4",
    shadow: "white",
    tertiary: "black",
  },
  CHEERIOS: {
    primary: "#e7cc03",
    secondary: "#212121",
    shadow: "black",
    tertiary: "black",
  },
  SMACKS: {
    primary: "#166055",
    secondary: "#fded48",
    shadow: "#black",
    tertiary: "black",
  },
  CRUNCH: {
    primary: "#112b7c",
    secondary: "fcfe4c",
    shadow: "black",
    tertiary: "black",
  },
  TOAST: {
    primary: "#d9b597",
    secondary: "#681577",
    shadow: "black",
    tertiary: "black",
  },

  FROOTS: {
    primary: "#4d96fc",
    secondary: "fffd23",
    shadow: "black",
    tertiary: "black",
  },
  BRAN: {
    primary: "#f1ad30",
    secondary: "fbfa00",
    shadow: "white",
    tertiary: "black",
  },
  KRISPIES: {
    primary: "#781500",
    secondary: "#f6ba6e",
    shadow: "black",
    tertiary: "black",
  },
  TRIX: {
    primary: "#fe0000",
    secondary: "ffffff",
    shadow: "black",
    tertiary: "black",
  },
  CHINA: {
    primary: "#ce2420",
    secondary: "#f8d12e",
    shadow: "black",
    tertiary: "black",
  },
  UKRAINE: {
    primary: "#f4ba00",
    secondary: "white",
    shadow: "black",
    tertiary: "black",
  },
  MEXICO: {
    primary: "#01563a",
    secondary: "white",
    shadow: "black",
    tertiary: "black",
  },
  GUATEMALA: {
    primary: "#3789bc",
    secondary: "#dde7ed",
    shadow: "black",
    tertiary: "black",
  },
  ICELAND: {
    primary: "#183889",
    secondary: "white",
    shadow: "black",
    tertiary: "black",
  },
  EGYPT: {
    primary: "#212121",
    secondary: "white",
    shadow: "white",
    tertiary: "black",
  },
  FRANCE: {
    primary: "#133970",
    secondary: "#ffffff",
    shadow: "black",
    tertiary: "black",
  },
  RWANDA: {
    primary: "#20603d",
    secondary: "#white",
    shadow: "black",
    tertiary: "black",
  },
};
