const PLAYER_TEAM_MAP = {
  AWESOMEX: "BRAN",
  KAWA: "TOAST",
  JR: "SMACKS",
  DETHORNE: "CRUNCH",
  ELFFAW: "SMACKS",
  "ANDY MAC": "TRIX",
  TWERP: "FROOTS",
  MATTAUX: "CHARMS",
  KAWA2796: "BRAN",
  PNKROCKJOCK26: "KRISPIES",
  HOOTENANNIES: "KRISPIES",
  OFTHEMOON16: "CHEERIOS",
  GOLFJBC89: "Turkeys",
  JMYRV: "CHEERIOS",
  MADSCOUTFAN: "CHARMS",
  MADSCOUT: "CHARMS",
  KURTZYP00: "TOAST",
  "KURTZY P00": "TOAST",
  "SNAKES ON A MICROPLANE": "FLAKES",
  EVERGREEN6258: "TRIX",
  "CREAM DADDY9057": "TOAST",
  FATKIDDESTROYERS: "FLAKES",
  NKSSOCCER15: "CRUNCH",

  ARMSTRONG: "australia",
  STORM: "australia",
  CHIPPER: "australia",
  COUGAR: "KRISPIES",
  FURY: "australia",
  CAVEMAN: "FLAKES",
  PONCHO: "india",
  SHEPARD: "india",
  CENTICE: "india",
  MIDDY: "india",
  OUTLAW: "CHARMS",
  SUNDOWN: "india",
  CASPER: "somalia",
  ICEMAN: "panama",
  SQUALL: "FLAKES",
  BOOMER: "FLAKES",
  JUNKER: "panama",
  SWABBIE: "panama",
  HOLLYWOOD: "switzerland",
  ARMSTRONG: "switzerland",
  TUSK: "switzerland",
  FOAMER: "switzerland",
  MYRTLE: "CHARMS",
  MARLEY: "thailand",
  RAINMAKER: "thailand",
  SCOUT: "thailand",
  BANDIT: "thailand",
  GERWIN: "CHEERIOS",
  TEX: "thailand",
  YURI: "venezuela",
  MIDDY: "venezuela",
  WOLFMAN: "venezuela",
  MOUNTAIN: "venezuela",
  SAMARA: "TRIX",
  STICKS: "somalia",
};

const TEAM_LOGO_MAP = {
  RLL: "assets/RLL_logo.png",
  TOAST: "assets/LOGO_CRM_DAD.png",
  BRAN: "assets/LOGO_RAISIN.png",
  CRUNCH: "assets/LOGO_CRUNCH.png",
  SMACKS: "assets/LOGO_SMACKS.png",
  TRIX: "assets/LOGO_TRIX.png",
  FROOTS: "assets/LOGO_LOOPS.png",
  KRISPIES: "assets/LOGO_KRISPIES.png",
  FLAKES: "assets/LOGO_FLAKES.png",
  CHEERIOS: "assets/LOGO_CHERRIOS.png",
  CHARMS: "assets/LOGO_LUCKY.png",
};

const TEAM_COLOR_MAP = {
  RLL: {
    primary: "crimson",
    secondary: "white",
    shadow: "white",
    tertiary: "black",
  },
  CHARMS: {
    primary: "#499f5a",
    secondary: "white",
    shadow: "fc5e00",
    tertiary: "black",
  },
  FLAKES: {
    primary: "#ff6534",
    secondary: "#3651a4",
    shadow: "white",
    tertiary: "black",
  },
  CHEERIOS: {
    primary: "#e7cc03",
    secondary: "#212121",
    shadow: "black",
    tertiary: "black",
  },
  SMACKS: {
    primary: "#166055",
    secondary: "#fded48",
    shadow: "#black",
    tertiary: "black",
  },
  CRUNCH: {
    primary: "#112b7c",
    secondary: "fcfe4c",
    shadow: "black",
    tertiary: "black",
  },
  TOAST: {
    primary: "#d9b597",
    secondary: "#681577",
    shadow: "black",
    tertiary: "black",
  },

  FROOTS: {
    primary: "#4d96fc",
    secondary: "fffd23",
    shadow: "black",
    tertiary: "black",
  },
  BRAN: {
    primary: "#f1ad30",
    secondary: "fbfa00",
    shadow: "white",
    tertiary: "black",
  },
  KRISPIES: {
    primary: "#781500",
    secondary: "#f6ba6e",
    shadow: "black",
    tertiary: "black",
  },
  TRIX: {
    primary: "#fe0000",
    secondary: "ffffff",
    shadow: "black",
    tertiary: "black",
  },
  thailand: {
    primary: "#07304f",
    secondary: "white",
    shadow: "black",
    tertiary: "black",
  },
  venezuela: {
    primary: "#ffbc00",
    secondary: "#cf142b",
    shadow: "black",
    tertiary: "black",
  },
  somalia: {
    primary: "##1980bf",
    secondary: "white",
    shadow: "black",
    tertiary: "black",
  },
};

const COLOR_MAP = {
  orangeTeam: rgba(223, 126, 0, 1),
  blueTeam: "blue",
};
